### ISSUE TITLE
What differentiates Mullvad Browser from, for instance, arkenfox's user.js or Librewolf?

### ISSUE THREAD

**Issue by asger-finding** [mullvad/mullvad-browser#1]
I definitely think this fork is a cool concept, but I don't particularly see the need for an extra browser binary when Firefox itself can manage multiple profiles in the first place (I have this stance on Librewolf too)

What demand is this browser supplying, that can't perhaps be solved with less redundancy? Maybe I'm answering my own question here, but seeing as Mullvad browser is a collaborative effort with Tor, is the effort effectively to match the fingerprint generalization that Tor browser does? (although Tor advises against uBO while Mullvad Browser comes with it preinstalled)

**Comment by noctuid** [comment]
Some questions regarding user.js:
- Some of the preference changes are listed on that page.  Is there some way to see the full list of about:config/user.js changes?
- Would it make sense to use mullvad-browser with something like arkenfox/user.js or pyllyukko/user.js?  Is the goal to not need any further user.js changes but to instead the "safer" or "safest" settings if desired?  Would changing some of these settings negatively affect fingerprinting?

**Comment by ruihildt** [comment]
> * Some of the preference changes are listed on that page.  Is there some way to see the full list of about:config/user.js changes?

Those are the two files used:
- https://github.com/mullvad/mullvad-browser/blob/mullvad-browser-102.9.0esr-12.0-2/browser/app/profile/000-mullvad-browser.js
- https://github.com/mullvad/mullvad-browser/blob/mullvad-browser-102.9.0esr-12.0-2/browser/app/profile/001-base-profile.js

001 is preprocessed, so it isn't exactly what users will get, but close enough, it has a few `#ifdef` to differentiate between platforms, especially for the font lists.

**Comment by Thorin-Oakenpants** [comment]
Disclosure: I am the owner of arkenfox (started 8+ years ago), have worked behind the scenes with librewolf the last two years (to get their prefs flips into some sort of sanity), and have also been working with (not for) Tor Project and Firefox on fingerprinting for the last five+ years

---

> the privacy model is about having a same fingerprint per platform for Mullvad Browser users, so you're not uniquely identifiable (which will be the case by following privacy hardening guides)

nit: if you do nothing you're already unique - you guys even quoted the same paper - as already pointed out for year(s) in the [AF wiki](https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-fingerprinting) - see the linked pdf that shows 99.24% uniqueness (without the IP data point). So to say the AF makes you more unique is false :)

The key with FPing protection is that ultimately everything can be rendered static (randomness can be detected etc - not to be confused with protecting the real value) - so the only way to protect against advanced scripts is to be in a crowd - the more the merrier (as this helps ensure the long thing tail gets fatter).

---

> Is it possible for websites to read all these settings

Yes. It only takes 20ms or less to run JS attack templates for browser capabilities - such as HTMLElement keys, navigator keys, css supported properties and so on.

PS: you do not need to disable webRTC, as it is already protected by mDNS and is gated behind user gestures - the user must also explicitly opt in per site, per session to start sharing. WebRTC support is trivial to fingerprint.

Don't change settings - in fact we (Tor Browser and flow on to Mullvad) will be locking them down more in future, and even making some prefs not be respected in code

---

If anyone wants a detailed breakdown of differences between AF/LW (which are almost identical these days) vs Mullvad Browser, then it's a short list. It's just a slightly different space - each with pros and cons. If it's not OK to do that here, mods please say so - I don't want to create noise

**Comment by Thorin-Oakenpants** [comment]
Here goes. This is a generalization and I'm not going to nitpick every individual difference

AF (arkenfox) vs LW (librewolf)
- AF enables SB (safe browsing) and uses mozilla's API key. LW doesn't have a SB key
- AF updates same as Firefox. LW has no updater in windows
- AF can use any language, LW is limited to en-US
- AF restricts cross-site referrers by default
- LW ships with uBO - AF users have to do that manually and add/flip the two recommended filters as per the AF wiki
- So basically everything you see at Arthur's independent test site at https://privacytests.org/ for LW applies to AF along with referrers (navigational) with a green check as well

---

I'll just use AF to also mean LW, and TB + MB to also mean the same thing

AF/LW vs MB (it's not a competition). 
- AF does not start in Private Browsing (PB) mode. Instead it can effectively achieve that in normal mode via sanitizing on close - and the threat model does go as far as trying to avoid all disk state (but you can do that in the optional OPSEC section)
   - This has benefits - such as being able to leverage containers (containers and PB mode are incompatible), being able to retain some login data (site exceptions are retained), being able to leverage private window sessions as another "container", having non-PB mode APIs available such as service workers
- AF uses dFPI and network partitioning, not FPI. FPI has some issues outside of PB mode, such as isolation of service workers. dFPI allows for site exceptions for cross-site logins

So all in all, that's 99% of the differences. Slightly different threat model re disk and using normal mode vs PB mode. Makes sense for MB to just piggyback on everything TB uses with a few tweaks. And AF allows customization to harden or relax because AF is not a crowd - also see point earlier about literally not being able to make things worse (99.24% and that's without the IP data point)

Now to fingerprinting. Since AF is not a crowd, it only aims, for now, to thwart naive scripts with randomized canvas, and with RFP does it's best depending on the number of users and the degree of the FPing script. Until RFP becomes front facing in Firefox, there isn't much more that can be done. But it will happen :) nudge nudge wink wink

Now there are difference in TB/MB's resistance vs Firefox's. There are TB patches waiting to be upstreamed - such as all the font work done by @PieroV et al - e.g. system font protections. And TB's bundled fonts are a superior solution to Firefox's font vis work, especially on Linux. Another major difference is in language protection where TB locks down the regional locale to match language (this is also awaiting upstream) - but Firefox RFP currently only handles en-US. Other TB patches will likely also land first at TB - such as scrollbar protections, storage.estimate quotas, newwin and LBing fixes, etc. And the big daddy of them all, webgl is click to play on TB (thanks to NoScript). AF disables webgl, as it has always recognized that this is extremely high entropy and there is no RFP solution to it (yet).

That's about it
- MB piggybacks on TB's hard work and threat model and uses FPI and PB mode, and HAS A CROWD for resisting fingerprinting - just grow that crowd - and benefits from early TB patches
- AF is a different threat model + space and while it encourages using a system VPN (not an extension), it has no crowd, allows configuration, and uses normal mode with sanitizing and dFPI and ETP benefits

sorry for the long post

PS: long term I am hoping we can retire arkenfox (I can't speak for LW) and just use MB - but they're just a little too divergent for now

**Comment by Thorin-Oakenpants** [comment]
AF/LW also use crlite as a superior privacy solution to OCSP

**Comment by Thorin-Oakenpants** [comment]
> Firefox is unusable for me for normal browsing without addons/setting changes

Indeed. The web without uBO is a cesspit :)  FF itself though is pretty good by default - we've effectively eliminated cross-site state tracing with partitioning - see the link to Arthur's test. Configure some sanitizing on close and this removes repeat 1st party tracking. We've also got some good progress on navigational tracking, but add a **_system VPN_** (extensions have holes <sup>1</sup>) and that eliminates the rest (referers, using CDNs) as well as adding a degree of anonymity. This already puts you in the too hard to deal with basket for 99% of cases (I made that figure up, gut feeling)

That leaves stateless as the last or next frontier. We _can_ beat it by making it too hard and too costly (lots of ways to do this) - but that's a topic for another day. For Firefox, ETP blocks known scripts (as does uBO), and in all honesty if you're happy with my made up figure of 99%, then so be it ;) RFP is not for everyone - but there are plans to make it more compatible in Firefox by allowing site exceptions and other patches to reduce breakage whilst still protecting. Just be patient - good things take time

There's nothing saying you can't use multiple browsers. I have FF portable stable with AF + nightly (installed with uBO + sanitizing on close) as my two man drivers. If something breaks in stable, I flick it open in nightly - they can run concurrently

I suggest using MB for as long as you want - bookmark fav sites that work perfectly in it and just run it side by side with Firefox - I'm going to use it as my third daily driver - just to help build some FP crowds :)

<sup>1</sup> https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names
> Important note when using extension-based proxy service: Extension-based proxy services usually are performed on the fly through a browser API. In such a case, uBO's DNS queries to uncloak canonical names will NOT be caught and proxied by an extension-based proxy service. So you may want to disable this setting when using an extension-based proxy service.

**Comment by ruihildt** [comment]
> but is it a problem to change firefox settings like browser.download.useDownloadDir and browser.autofocus? Similarly, would it be a problem to do something like switch to dark theme?
> 
> It might be nice if the documentation was more detailed regarding best practices and things that should be avoided. Is the recommendation just to make absolutely no changes to settings/addons/themes/etc. if the goal is to maintain as similar a fingerprint as possible?

@noctuid I now see I never addressed these points.

We plan to improve the documentation as we go, and our FAQ will grow as we receive questions and feedback from users.

There is a will from Tor Browser and Mullvad Browser to better explain what impact has a specific change in terms on privacy. It's not clear yet as to how/when it will materialize.

The reason this has not yet been done is simply a question of time and resource.

**Comment by felschr** [comment]
https://privacytests.org now includes results for Mullvad Browser that can be compared to Librewolf, Tor Browser, etc.

**Comment by ruihildt** [comment]
Closing this issue as questions have been answered.

Feel free to open another issue if needed.
