### ISSUE TITLE
Doesn't work on Musl C

### ISSUE THREAD

**Issue by Arzumify** [mullvad/mullvad-browser#115]
Title. Would it be possible to release binaries compatible with musl c as well as glibc?

**Comment by ruihildt** [comment]
This is depending on Firefox and Tor Browser to support first.

**Comment by Tracker-Friendly** [comment]
They do…

**Comment by ruihildt** [comment]
I have just confirmed it's not possible with Tor Browser and nothing has changed since the following issue has closed: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/23117

If you want to argue your case for changing this, I invite you to discuss directly with the Tor Browser developers.
