### ISSUE TITLE
Random padding in viewport

### ISSUE THREAD

**Issue by nona-mousy** [mullvad/mullvad-browser#118]
Hi all,
 
i'm having a problem, where there is some padding being added to the viewport.

This issue only occurs if the viewport dimensions aren't exactly a multiple of 10 (e.g. 1300px / 450px is fine).

<img width="1512" alt="Screenshot 2023-07-29 at 23 35 58" src="https://github.com/mullvad/mullvad-browser/assets/134346897/b2498d4e-1636-48ae-befe-433b3fb17f5e">

<img width="1512" alt="Screenshot 2023-07-29 at 23 30 15" src="https://github.com/mullvad/mullvad-browser/assets/134346897/c6106f6b-c250-4978-9c71-94b3de36531d">

(don't mind the black bar, forgot to hide my bookmarks...)

Mullvad Browser: 12.5.1 (based on Mozilla Firefox 102.13.0esr) (64-bit)
macOS (Ventura 13.4.1): Darwin 22.5.0 arm64

**Comment by iam-py-test** [comment]
This is not a bug. It is a feature named Letterboxing which is designed to hide the real size of your screen
https://support.torproject.org/tbb/maximized-torbrowser-window/

**Comment by Thorin-Oakenpants** [comment]
the steps are actually 50, 100, 200 and differ for width and height
- https://hg.mozilla.org/mozilla-central/rev/6d2d7856e468#l2.32

if you really hate it, because you resize the browser window, and can justify the fingerprint "risk" (it's not a risk, it is a FACT = **every script out there will grab this metric so you will really stand out** [1]), then
- open `about:config`
- type `privacy.resistFingerprinting.letterboxing` into the search box
- if it already exists toggle it to false
- if it doesn't exist then add it as a boolean and change it to false

upstream tor project is still looking at how to explain this (so you wouldn't have to ask 😄 ) and to provide a UI to turn it off (maybe). And other things we can do to perhaps not force users to resize (such as expanding the max width on new windows) .. etc

[1] you would only stand out if you changed from the newwin size (assuming newwin is a perfectly expected size = almost identical to the steps for letterboxing, see link above). So in theory, you could disable it, do most of your browsing in the standard window, but maximize for some sites then flick back (no letterboxing shown) - i.e is relying on OpSec and no bugs in newwin

**Comment by tiara-adessi** [comment]
I'm sinking into my own puddle of shame 😫 I'm so sorry... I've read the FAQ right before reading this and it states so explicitly. It takes some getting used to. Thank you guys!
