### ISSUE TITLE
scaled-resolution-friendly letterboxing

### ISSUE THREAD

**Issue by metafiziks** [mullvad/mullvad-browser#15]
the letterboxing on, say, a 1280x800 resolution (figure-A) looks fine, but on an increased resolution like 1024x640 (figure-B), the letterboxing takes about ~10% of the bottom screen real estate. any way to make it more accessible (e.g., re-distribute 2.5% to each side)? there might not be, right? the letterboxing has a somewhat pre-defined width and height? it's probably been asked in the tor stackexchange

---

figure-A
<img width="1392" alt="figure-A" src="https://user-images.githubusercontent.com/128985798/229649783-5ed82b13-ba19-49c6-8a18-033967134c0c.png">

---

figure-B
<img width="1136" alt="figure-B" src="https://user-images.githubusercontent.com/128985798/229649787-e8f97b02-1a66-479e-b9d6-ab942a364bec.png">

**Comment by Thorin-Oakenpants** [comment]
There's no easy answer. People have different native screen resolutions, different system scaling settings and other OS changes such as test scaling which can affect UI heights, different taskbar/docker positions and their widths/heights, different chrome settings (chrome being browser parts that aren't the web content) such as sidebar open or bookmark toolbar always showing, etc - that there is literally a plethora of possible results for what space is actually available for the viewport

Some people will get a small matte (bottom or sides), others will lose a large chunk of real estate. When we did this I proposed stepping smaller steps at lower sizes then medium then large - this would keep the number of overall possible sizes (e.g resizing, maximizing, full screen etc) much the same (as if we did one step size), but allow for tighter fits at lower resolutions. Since most users stay at lower resolutions (i.e 1000 x 1000 and under), there are actually more buckets. If we reduced it even further to smaller steps at lower sizes, then we're just going to make more buckets of users by splitting those we already have

**Comment by metafiziks** [comment]
ah, interesting. thanks irregardless!

**Comment by gamer191** [comment]
> If we reduced it even further to smaller steps at lower sizes, then we're just going to make more buckets of users by splitting those we already have

Can I suggest decreasing the fingerprinting surface by hardcoding the possible width:height ratios

**Comment by Thorin-Oakenpants** [comment]
> then I get a completely unique fingerprint, according to coveryourtracks.eff.org

Please don't use these site to calculate entropy - they are completely full of shit. Use em to read what values you return, but that is it

> by hardcoding the possible width:height ratios

ratio is immaterial - the entropy is width and height. There is no need to complicate it with calculating one based on the other when it's already limited by other constraints

anyway, we changed the max newwin sizes to allow for a widescreen'ish size (1400x900) since that's basically all today's desktop/laptop screens (orientation aside) and this gives more real-estate and effects pages to display as non-mobile content (there's some nasty ill-thought 1024 or so pixel size they all want to use to determine css rules)

and the followup we have an idea to collect via Mozilla what inner sizes users actually use, and to be smarter about what sizes we offer - such as a smaller selection of snap-to-sizes under 1400x900
