### ISSUE TITLE
Page does not take up the entire window; strange borders

### ISSUE THREAD

**Issue by alejandro5042** [mullvad/mullvad-browser#152]
For whatever reason, the browser has always had some weird borders around the page.

Examples:

![image](https://github.com/mullvad/mullvad-browser/assets/3143819/0fd5b1ca-9bff-4e81-a172-a23a5c103e92)

![image](https://github.com/mullvad/mullvad-browser/assets/3143819/1e6b480d-f824-4242-89c0-d280068049ee)

They change size whenver you resize the browser.

Here's the version:

![image](https://github.com/mullvad/mullvad-browser/assets/3143819/95360104-2499-4921-b95a-b498b6aac733)

Running Windows 11 (22H2).

**Comment by iam-py-test** [comment]
This is a feature called Letterboxing which hides your real screensize: https://mullvad.net/en/help/tag/mullvad-browser/#104
Thanks

**Comment by grand-lotus-iroh** [comment]
It's bewildering that there isn't an easier option to deactivate this feature. Such a minor aspect significantly undermines the credibility of the entire project, especially when it's enabled by default.

Enter `about:config` into address bar and edit `privacy.resistFingerprinting.letterboxing`
* https://mullvad.net/en/browser/hard-facts

**Comment by ruihildt** [comment]
@grand-lotus-iroh Doing so will change your browser fingerprint and most likely will make you stand from other users.

We are aware the experience is not great and are currently experimenting new ways to improve it.

**Comment by AroundThisWorldAgain** [comment]
@ruihildt -- Screen resolution is not very unique unless you're doing something really weird, such as me running a custom resolution cutting off the right 10px of my screen because they're dead.

Enabling this feature by default just makes the browser look like it's broken.  If people care *that much*, they'll can enable it.

**Comment by ruihildt** [comment]
> Screen resolution is not very unique unless you're doing something really weird, such as me running a custom resolution cutting off the right 10px of my screen because they're dead.

This is protecting is the page content dimensions (also called "viewport"), not only the screen or window size. This will changed based on whether you have a bookmark toolbar, etc.
It's inconvenient, but it is needed to diminish uniquely identifiable information the browser already provide and make good the model of hiding in the crowd.

Mullvad Browser is a privacy-focused browser,  so we will keep this letterboxing enabled.

In Mullvad Browser 13.5, there will be some quality some improvement in terms of convenience and design (see below).

It will also be possible to remember the previous window size, so if you prefer to downsize the window to hide the letterboxing, then next time the browser is started, it will remember your preference instead of resetting to 1400*900.

![image](https://github.com/mullvad/mullvad-browser/assets/13787166/20915baf-b055-4a60-8e30-937fe0cc6895)

**Comment by Thorin-Oakenpants** [comment]
@AroundThisWorldAgain you need to educate yourself

Lets look at the variables - because this protects not just screen, but available screen, and outer window .. and inner window (viewport).
- we'll start with a multitude of various native screen resolutions
- now add the position of the dockerbar/taskbar (side or top/bottom)
- now add variation in height or width (e.g. in windows 10 you can double height it or choose any width if on the side)
   - height will differ in say win7 vs win11
- now lets look at the browser's chrome
   - you can enable/disable the titlebar
   - you can enable/disable the menubar
   - you can enable/disable the bookmarks toolbar
- lets look at density
   - compat, normal, touch all change the chrome dimensions
- lets look at app scaling
   - such as large text, or changing the pixels per css
   - these also change measurements
- lets add in system scaling
   - this changes everything
- lets add in zoom on a webpage
- let's add in toggling on docked console, sidebar ... these also affect measurments
- now lets let the user use any size they want
   - manually resize, maximize, fullscreen

The sheer number of possible results here are in the millions, in fact more possible combos than users

There is no such thing as "not very unique" - why do you think it's a protected metric in TB/MB and why do you think it's grabbed by every single fingerprinting script out there. Do you not think that **_actual experts_** have not examined and understood the problem? **do not answer** - it is a rhetorical question

**Comment by AroundThisWorldAgain** [comment]
LMAO.  blah blah blah.

This is all paranoid bullshit.  I work at a FAANG.  Billions of hits.  I just checked our logs.  We have 2,190 unique desktop resolutions in the past month, and 187 account for 95%.

You made an idiotic product decision for the illusion of privacy.  But please, by all means, feel free to continue being idiots about it.  I'm unsubscribing.  Bye!

**Comment by Thorin-Oakenpants** [comment]
> I work at a FAANG

so what! do you think that makes you an expert in this field? You truly are ignorant. You're looking at screen size which is the the _starting point_ - you're not accounting for available screen but more importantly inner window

> Fingerprinting on window size is not

yes it is - I _know_ it is

> I'm unsubscribing. Bye!

awesome, make sure not to reply anymore or we'll secretly know you're still here and learning
