### ISSUE TITLE
Allow Google as a search engine?

### ISSUE THREAD

**Issue by pczern** [mullvad/mullvad-browser#179]
When I click in the URL bar, it is not possible to add Google to the search engines.
I know it's a private browser and Google is not too private, but using this browser is still more private than using any other browser even if we'd use Google from time to time?

**Comment by ruihildt** [comment]
> When I click in the URL bar, it is not possible to add Google to the search engines.

It seems that Google doesn't provide an [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) [standard mechanism](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox) to add it to Firefox based browser.

They do provide it for YouTube, so this seems intentional.

We will review internally whether we should include it to the default list of search engines and in the meantime you probably can use a webextension to add Google as a default search engine.

**Comment by ruihildt** [comment]
@jonaharagon There are actually some extensions doing just that, but it's hard to recommend a third party extension seemingly from a "random" person, which could be updated and changed at any point in time.

For completedness, Google has an opensearch file available, it's just not linked on their homepage.
https://www.google.com/searchdomaincheck?format=opensearch

**Comment by ruihildt** [comment]
Another relatively simple approach is to create a simple html page and link in its <head> section the Google opensearch document. This way, users could right-click on the page and add it.

(This is the approach taken by https://addons.mozilla.org/en-US/firefox/addon/search-engines-helper/)

**Comment by ruihildt** [comment]
Right now there's no plan to add Google Search as part of the default search engines.

Here's a zip containing an HTML file (since I can't add an HTML file to Github comments) you can download and open in Mullvad Browser to add Google to the list of available search engines.

[google-search.zip](https://github.com/mullvad/mullvad-browser/files/13363207/google-search.zip)

And here's the full HTML code:

```
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8" />
    <title>Add Google as a default search engine</title>
    <link
      rel="search"
      type="application/opensearchdescription+xml"
      href="[https://www.google.com/searchdomaincheck?format=opensearch](view-source:https://www.google.com/searchdomaincheck?format=opensearch)"
      title="Google Search" />
  </head>
  <body>
    <main>
      <h1>How to add Google Search Firefox-based browsers</h1>
      <ol>
        <li>Right click in your URL bar.</li>
        <li>Click "Add Google".</li>
        <li>Google has now been added to the list of search engines</li>
        <li
          >To change your default search engine, go to "Menu" > "Settings" >
          "Search" > "Default Search Engine"</li
        >
      </ol>
      <p>Note: if Google Search is already an option, when you right-click, nothing will show up</p>
    </main>
  </body>
</html>
```
