### ISSUE TITLE
website: windows downloads: win10+ qualification is ambiguous

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [mullvad/mullvad-browser#25]
https://mullvad.net/en/download/browser/windows

says on the tin
> Works on Windows 10 or later (64 bit only)

It actually works on windows 7 or later, and is discouraging some windows users. I don't expect this to change until ESR128

edit: unless the windows 10 has something to do with the VPN part, in which case it's confusing

**Comment by Minimalist73** [comment]
I guess that they don't want users to use the browser on a "deprecated" operating system. The VPN application dropped support for older Windows version since [version 2022.1](https://github.com/mullvad/mullvadvpn-app/releases/tag/2022.1) ([Blog post](https://mullvad.net/en/blog/2022/2/14/ending-support-windows-7-8-and-81-our-app/)) so it can explain why they set that to W10.

**Comment by Thorin-Oakenpants** [comment]
I'm not a VPN expert, but there are questions around the system VPN vs extension VPN, indeed I dropped hints about extension limitations in https://github.com/mullvad/mullvad-browser/issues/1#issuecomment-1496120477 

some else smarter than me said
> however I think the Mullvad extension in Mullvad browser is not meant to be used as the in-browser VPN but they expect you to run the VPN globally. I say this because there's no UI for connecting to the VPN in the browser itself, or at least I couldn't find it.

anyway, since the site actually "encourages" (IDK if that's the right word) users to use the browser without the VPN as well, I think the wording could be modified - it _is_ discouraging users (I have seen comments saying they can't use it because they are on win7) and will do so for over a year to come - which is at odds with Tor Browser itself

"Requires windows 10+ for VPN" or similar seems better - I'll leave it up to you guys

**Comment by ruihildt** [comment]
The supported versions on the website corresponds to the platforms we test.
We currently test on the following platforms:
- macOS 12 (intel / arm)
- macOS 13 (intel / arm)
- Fedora 37 (Latest version)
- Ubuntu 22.04 (Latest LTS)
- Windows 10
- Windows 11

Because testing takes time and resources, we decided to only test on the platforms we support.

Outside of the listed platforms, the Mullvad VPN and Mullvad Browser may work. Since we don't test, we can't be sure and in turn we can't recommend it.

I think I understand the case for changing the wording, so I'll bring this point internally and will provide an update when I have an answer.
