### ISSUE TITLE
Extension icon doesn't show up and Extension button is missing

### ISSUE THREAD

**Issue by lamyergeier** [mullvad/mullvad-browser#262]
As described in Firefox documentation: [Extensions button in the toolbar](https://support.mozilla.org/en-US/kb/extensions-button) (see the link) is not visible on the latest Mullvad browser. 

I have installed some extension as can be seen below, but there is no way to show up (pin) extension icon (e.g. Video Downloader Helper).

![image](https://github.com/mullvad/mullvad-browser/assets/42092626/b9eed323-5254-423a-98e0-45a4ce259585)

**Comment by ruihildt** [comment]
See https://mullvad.net/en/help/faq#115

(The purple mask icon in your screenshot indicates that the corresponding extension has been allowed to run in private browsing mode)

**Comment by lamyergeier** [comment]
@ruihildt  So for every extension we must enable it to work in private mode? Is mullvad browser by default works in private mode?

**Comment by Thorin-Oakenpants** [comment]
@lamyergeier by default MB starts in Private Browsing mode. By default when you install extensions, you are prompted to allow to run them in PB mode - otherwise you can set this via about:addons - for the extension(s) in question, click the 3-dot menu `. . . ` and select `manage` .. and change the setting there

![example](https://github.com/mullvad/mullvad-browser/assets/16656956/daf838df-eef7-4f4a-90b0-c550346a03e2)
