### ISSUE TITLE
Your MullvadBrowser profile cannot be loaded. It may be missing or inaccessible on Windows

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#28]
> i've just downloaded and installed the mullvad browser on a windows 11 machine. the browser will not launch and generates error:
> 
> Your MullvadBrowser profile cannot be loaded. It may be missing or inaccessible.
> 
> i have installed it in a directory other than the default on the setup page. the install directory is: C:\Program Files\applications\mullvad browser
> 
> is it possible to launch the browser with the option to create a profile, i.e. with a -p option as in firefox? my firefox profile is on a data drive, other than where the program is installed. i have full administrator privileges, have downloaded the program twice from you website, and attempted to install it three times with the same result.

**Comment by dabljues** [comment]
Same for me. After installing on Desktop, everything works. But it's kinda silly to have it on Desktop.

**Comment by Saxar88** [comment]
I have the same issue.

**Comment by ave9858** [comment]
This seems like a permissions issue. I was able to reproduce the issue by installing into Program Files and running the installer as admin. Running the installer as non-admin causes the install to fail. Since the directory where the browser is installed is also the default profile directory, the profile fails to be created as the browser does not have permission to modify the program files directory. Adjusting the permissions of the install directory does work, but introduces a potential security problem as any user could tamper with the browser for all other users. Instead, a better workaround is creating a new profile in a directory that is writable by the current user only, for example the documents folder. If you are the only user who needs mullvad browser, installing it into a folder inside your user folder is probably a better idea. `mullvadbrowser.exe -p` should let you manage profiles and create a new one in a writable directory.

**Comment by Saxar88** [comment]
Yes, I can confirm. It works after installing it in the "Documents" folder.

**Comment by 0strodamus** [comment]
This is also a problem on Linux when installed to the standard locations (in my case /usr/lib, but I'm pretty sure /opt would also fail). Hoping this restriction will be lifted in a future version.

**Comment by CaptainBride** [comment]
I installed it in the Program Files folder, but I had to specify the "compatibility" tab, "run this program as an administrator", then everything is fine

**Comment by ave9858** [comment]
> I installed it in the Program Files folder, but I had to specify the "compatibility" tab, "run this program as an administrator", then everything is fine

Not sure if running a browser as admin is a good idea or even supported.

**Comment by cymax95** [comment]
> The newest 13.5 update has caused this issue. It was fine before the update. Reinstalling the browser doesn't seem to fix it. I'm using the Flatpak on Fedora 39 if that helps.

I can confirm having the same issue. I am using Flatpak on PopOs. Reinstalled. Tried to purge all data with flatpak and it still says the same message when launched:

Your MullvadBrowser profile cannot be loaded. It may be missing or inaccessible.

**Comment by ruihildt** [comment]
@drakelight @cymax95 This issue is related to Windows.

You current issue is being fixed by an update to the flatpak package, but it has not been deployed yet.
 See: https://github.com/mullvad/mullvad-browser/issues/265

**Comment by cymax95** [comment]
> @drakelight @cymax95 This issue is related to Windows.
> 
> You current issue is being fixed by an update to the flatpak package, but it has not been deployed yet. See: #265

Thank you. The update resolved my issue.

**Comment by FabianLoRs** [comment]
same problem on linux mint
