### ISSUE TITLE
Weird squares on maps.google.com.

### ISSUE THREAD

**Issue by Giger22** [mullvad/mullvad-browser#290]
I noticed weird squares when viewing maps.google.com. The same thing happens when using LibreWolf and Tor Browser.
![maps](https://github.com/user-attachments/assets/5e63c64d-2604-4403-964e-d52fea62c36b)

**Comment by iam-py-test** [comment]
This is a feature called Letterboxing which hides your real screensize: https://mullvad.net/en/help/tag/mullvad-browser/#104
Thanks

**Comment by morganava** [comment]
@iam-py-test not quite, the user is referring to the little squares in the map itself.

@Giger22 the solution for this (and similar looking issues on other websites) is to allow the website the 'canvas read' capability. There should be a little icon in the URL bar:

![image](https://github.com/user-attachments/assets/c3370e4d-469e-4c5b-820e-36fe5816870d)

Mullvad and Tor Browser by default prevent the website from reading data from the HTML canvas, because doing so can allow websites to fingerprint various aspects of your computer setup. Presumably, Google is rendering highway symbols client-side in a canvas, reading them back from that canvas for display on the map (rather than rendering/downloading images server-side).

**Comment by iam-py-test** [comment]
Thanks @morganava 
Sorry for misreading the post.
