### ISSUE TITLE
Cannot Import Firefox data

### ISSUE THREAD

**Issue by MrPaz** [mullvad/mullvad-browser#310]
Mullvad 13.5.3 on Windows 10

Firefox is my daily driver.  When I navigate to Settings > Import Browser Data and click the Import Data button, Firefox does not appear in the list of browsers (only Chrome and Edge).

Also, I only see the option to import Bookmarks.  Is this intentional?  I would also like to import passwords, autofill, history, etc.

![image](https://github.com/user-attachments/assets/3776c7a2-8e04-453a-84d3-474e8d6c88f6)

**Comment by MrPaz** [comment]
Is there a workaround to manually import all FF data to Mullvad?

**Comment by Thorin-Oakenpants** [comment]
Firefox as an option doesn't appear in Firefox either: am on windows with a Firefox registered as an app and set as my default browser (albeit it is portable and points to the firefox-portable.exe - so that may have a bearing). My installed Firefox nightly doesn't show any Firefox profiles to import, and I also have an installed Beta version

My best guess is this is an upstream Mozilla issue or design decision?

Meanwhile you can import bookmarks (and in MB14+ passwords, but MB doesn't retain passwords so don't bother) from a file

To export bookmarks
- hamburger menu > bookmarks > Manage bookmarks (down the bottom)
- in the library dialog .. Import and Backback > export bookmarks to HTML

Then in MB you do the same but choose "import bookmarks from HTML" - this will replace all your bookmarks

**Comment by MrPaz** [comment]
Pardon my absence.

> My best guess is this is an upstream Mozilla issue or design decision?

Is this a design decision?  If so, why?  

Or maybe it makes sense that MB can't find standard FF since it's a fork of FF (it'd be looking for 'itself')....?  But it sure would be nice to have that seamless import experience.

> (and in MB14+ passwords, but MB doesn't retain passwords so don't bother) from a file

Why doesn't it retain passwords?  Or say credit card autofill data?  Yes a PW manager is superior, but there's use cases for these features regardless.  Is there other reasons this is a no-no?  I don't think I will use MB as daily driver without and will stick with FF.

**Comment by Thorin-Oakenpants** [comment]
> If so, why?

I don't work for mozilla. Just pointing out that AFAICT Firefox doesn't detect any other Firefoxes (and I have at least two installed and three registered as apps, and lots of portable ones)

> Why doesn't it retain passwords

Because the file `cert*.db` is also used for storing other (unique) state .. namely certs .. which can be used for fingerprinting
