### ISSUE TITLE
Jitsi doesn't work on a specific server

### ISSUE THREAD

**Issue by Kobaxidze256** [mullvad/mullvad-browser#347]
I want to use Jitsi but based on my testing on Librewolf, it seems I need privacy.resistFingerprinting set to false. So I created a separate profile but the pref is locked.

**Comment by Thorin-Oakenpants** [comment]
Have you tried to just allow a canvas exception instead (the site exception will remain for the session only). In my experience/knowledge, this is the only RFP protection that affects WebRTC

Anything else is likely to be security slider based (webgl is required for some services) or some other setting/restriction (e.g. we don't ship Cisco's Open h264 plugin, something something about webRTC settings)

**Comment by ruihildt** [comment]
Can you check if Jitsi works for you in the [latest alpha](https://github.com/mullvad/mullvad-browser/releases/tag/14.0a10)?

I have tested on my side this morning, without making any change to the default install, and it worked properly.

**Comment by Kobaxidze256** [comment]
@ruihildt @Thorin-Oakenpants nothing you've said helped

**Comment by Kobaxidze256** [comment]
> Could you please detail the following:
> 
>     * OS
> 
>     * Mullvad Browser version
> 
>     * Steps to reproduce your issue (website used, what is expected to work, what doesn't)

* Arch Linux
* 13.5.9
* Open https://meet.gtk.ge/test in Mullvad Browser and something like Ch🤮romium, and observe Jitsi restarting in Mullvad Browser.

**Comment by ruihildt** [comment]
I have tested Jitsi on https://meet.domain.tld/test and another private Jitsi instance, and it's working for the other instance.

So I think it's not an issue with Mullvad Browser and Jitsi, but an issue with this instance configuration. I recommend you contact the admin of this instance to fix it.

_(I have also changed the URL of the Jitsi instance, because it can be freely accessed by anyone)_
