### ISSUE TITLE
Disallow anything that alters browser fingerprint

### ISSUE THREAD

**Issue by sycam0r-e** [mullvad/mullvad-browser#45]
Thank you for creating the mullvad-browser, this could be a huge step for online privacy. 

As I understand, the main mission of Mullvad Browser is to drastically increase online privacy, mostly by making it very hard for websites to fingerprint users based on their browser configs (I set aside the IP issues here).

Based on this understanding, I feel like it would be useful if Mullvad Browser disallows the user to change anything that would alter the fingerprint.

Think about it. If you let users be able to e.g. un/install addons the anonymity sets get smaller and smaller. Also, the warning when entering `about:config` needs to be much stronger / in line with Tor Browser. Users must be educated to _not_ randomly change configs. It's already happening, e.g. see [here](https://github.com/mullvad/mullvad-browser/issues/27).

I therefore propose to
- make it impossible to
  1. uninstall ublock origin (like noscript).
  2. change ublock origin's settings if doing so changes the fingerprint (again users are already training there Mullvad ublock see [this](https://github.com/mullvad/mullvad-browser/issues/37).
  3. uninstall the Mullvad addon if that changes the fingerprint.
  4. install additional addons (again already happening, see [here](https://github.com/mullvad/mullvad-browser/issues/26).
  5. change `about:config`.
  6. customise asthetics. 
- if any of the above is not sensible, instead _warn_ users to not do it.

Also improve the documentation to educate users in this regard. I feel like users must understand and treat Mullvad Browser just as the Tor Browser. That means don't fiddle with configs and understand certain design choices (see [here](https://github.com/mullvad/mullvad-browser/issues/43) for an example of docs not reaching the user).

My points are all mute of I misunderstand mullvad-browser's mission so feel free to correct me here. If I don't, I just fear very much that users (ab-)use it as yet another tweak-everything-to-my-specific-needs-and-make-me-stand-out - everyday browser which would ultimately destroy the mission.

**Comment by Thorin-Oakenpants** [comment]
This is an upstream issue with Tor Browser, and there are ongoing efforts to tighten some things (such as removing some UI settings, and locking some prefs, and looking at bypassing prefs in code) - if we wanted we could remove all of it (user changes), but that's not practical or particularly friendly, especially for testing purposes. This is also not just locking everything down, which is not the answer, education and intervention are the other ones.

Tor Project is already aware of all the things that users can change and how they affect usage and fingerprints

If you have specific ideas and want to contribute solutions or show examples of FPing via user actions, then please log tickets at https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues - i.e I am not saying don't speak up, but addressing the issues in TB means they get addressed in MB - thanks

> make it impossible to uninstall uBO
- https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/163

**Comment by Thorin-Oakenpants** [comment]
> make it impossible to change ublock origin's settings

I opened https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/164 but inadvertently marked it as confidential, someone will fix that in due time

**Comment by elandorr** [comment]
This is an abhorrent idea. The user must stay in control and be able to change settings, if he so desires.

You're just replicating google/dystopia.

Stop treating people like complete retards, and they will stop behaving as such. Instead of the useless 'advertising' on open like in plain TBB, there could be a single line of text stating 'Changing settings may reduce privacy benefits. Click here for details.' With a short write-up explaining some terms the user can research himself, if he wants.

Also 

> this could be a huge step for online privacy.

shows a complete lack of understanding. This is nothing special. This is a marketing tool for Mullvad, with TBB likely being paid for it.

It's a 'nice-to-have' for when you're lazy and want a standardized Firefox like the TBB, but on clearnet/VPN. It's not 'Mullvad browser'. It's Firefox with TOR's config and addons pre-installed.

You can achieve the same thing yourself with the regular TBB:

`TOR_SKIP_LAUNCH=1 TOR_TRANSPROXY=1`.

Nice, but don't hype it up.

Also, forget about the fingerprint madness that's going on in the issues posted here. That's not a thing anymore. You are not going to get that 'perfect', ever. Turn JS off completely for a start. Even then, there are various tricks using CSS that you cannot escape. FF does not have a config option for disabling CSS last time I checked.

It's just a 'nice-to-have'. That's all.

**Comment by ruihildt** [comment]
This first release of the Mullvad Browser is a starting point: there is still a lot that needs to be figured out.
To provide a privacy focused browser good enough to be used by most people, there are multiple ways to do it.

That's why I'm thankful for hearing different perspectives. Please let's keep the discussion civil.

**Comment by elandorr** [comment]
I did not try to offend anyone, but be honest and clear.

You cannot improve anything.

The only thing you could potentially think of is finding a way to disable CSS browser-wide. Not by using JS to turn off styles via an addon or userscript, which might trigger too late.

Granted, CSS is not a 'straight-forward' way to track like the many others, but with the next CSS spec and Mozilla/Google rushing to implement every buzzword past, present, and future, it's clear this is a futile struggle as it will become commonplace.

This explains a general idea that cannot be beaten: https://csstracking.dev/.
This is even simpler 'just' based on 'features': https://noscriptfingerprint.com/.

The only current counter-argument which is listed on the first link is already invalid:

>Currently, this method is not scalable as it requires over 1MB of CSS downloads and hundreds of requests per user

As even the 'simplest' modern website routinely downloads several MB and causes at least several dozen requests. The mainstream internet hipsters also created an environment where it's completely 'normal' to exclusively use randomly generated ids and entire subdomains.  
Blacklists are useless against an attacker that's motivated even a little bit.

You can track people successfully via CSS. But you don't have to:  
JS is effectively required to do _anything_ on the internet today,

As soon as you have JS enabled, it takes me (or even some greedy corporate duck who has no clue besides searching Google) just a few minutes to circumvent uBlock Origin or any other popular method using a self-written proxy. There are companies offering this as a service for a few bucks, it's not some 'secret' CIA crap, it's accessible to everyone willing to search for a few minutes.

At this point in time, you would have to dissect every individual JS call, and get rid of CSS, and that's not feasible.

This game is over, done for, finished. You simply have to boycott trash and violently reject modernity. A plain non-CSS HTML website or gopher don't have these issues. But how many websites can you name that are functional without either?

Set the TBB safety level to 'safest', and see how that goes in your daily life. Even this level isn't 'safe-safe'.

VPNs/blacklists/etc. are still 'fine' against annoyances like mainstream ads or for P2P applications. Just never think you're private in a browser today.

It would be pretty neat, if the TOR people considered creating a new panel that lets you define the lowest level environment used by CSS/JS, so we can definitively replicate a standard environment. But that is a huge task with the situation changing almost daily. On top of that, Firefox is gigantic bloat. Its codebase is so enormous, if you read their bugtracker you find that even their own paid corporate devs are confused half of the time. Doing this right would require a lot of resources. At that point, an org considering this might just build a new browser with only essential functions.

Also, it wouldn't really be useful. The internet is owned by cloudflare and google for the most part, and if you really were perfectly identical, you wouldn't be able to access most of the sites you're forced to. TOR is already almost unusable for browsing non-onion sites. If you aren't stopped by recaptcha or similar, you have your accounts banned and police on your ass. (Don't use paypal or similar via TOR... neither their support nor police have the slightest idea what TOR is, but they see a big red 'alarm' in their backend.) Mullvad is also already big enough to be on many blacklists.

If anyone still believes it's honest to hype this stuff up, I'd love to see some factual argument showing a yet-to-be-seen practical technique that evades tracking.

As usual this topic is just exploited for marketing and/or ego for internet peen.

As a sidenote: With things like the EU dictatorship's new PSD/2 you can forget about this altogether. If you still want to live, that is. Most of their forced modern abuse only runs in default environments. The only solution is to insist on paper, cash, real oldschool ways. If there aren't enough people standing up against it, this will only get even worse. Sweden already has no cash and forces you to run around with spy chips 24/7 to have even the most minimal life.

Cheers

**Comment by gsture** [comment]
> Stop treating people like complete retards, and they will stop behaving as such.

I am sorry to break it to you but most people on the internet are complete retards and don't read or think by themselves even if you give them information on a silver platter.

I think this idea is for the best. If you want to customize a browser you can use firefox or whatever other browser you want because you don't care about fingerprinting anyway.

**Comment by MNarath1** [comment]
I feel like as pointed out above people also like to use this browser because its simple firefox without alot of its telemetry crap and if you like it for that you might want to reenable some stuff that is disabled because of fingerprint reasons  or maybe install some additional extensions but that should always stay ones own decision not something that should be forced upon anyone yes people could just use the tor browser with the proxy disabled but why even make it neccasary when there is a similar browser already there to use. Basically if you want to warn people that changing these options might decrease their privacy thats fine but don't take that decision completely out of their hands.

**Comment by ruihildt** [comment]
I will close this issue, as it has been partly addressed, and the rest is/can be tracked in separate issues.

As a summary, it's unlikely that we will lock *everything* (whatever that means) altering the browser fingerprint but we will occasionally lock some preferences if we feel it's warranted. When we take such decisions, we'll explain our rationale and be transparent about it.
The rest of the time, we'll favor educating users about the potential impact of making a pref change, either contextually in the browser or through documentation.

We can (and will) be wrong and we are (and will) be listening to feedback in order to fix what needs fixing.
