### ISSUE TITLE
Unique media devices?

### ISSUE THREAD

**Issue by noctuid** [mullvad/mullvad-browser#5]
I notice I have a unique fingerprint on https://www.amiunique.org/fp, https://coveryourtracks.eff.org/, and https://browserleaks.com/canvas.  The canvas signature is unique but changes each refresh, so that's fine, but "media devices" also shows as unique for me.  Is that an issue?

**Comment by Thorin-Oakenpants** [comment]
it's not unique - all Mullvad (and TB, and RFP users) will report 1 audioinput and 1 videoinput

Test sites like this are not real world, have small data sets trained by privacy enthusiasts with tainted data (compounded by said privacy testers repeatedly testing and tweaking), and do not take into account how FPing protection in reality works (not knocking the site, it's just the nature of the beast) - i.e you cannot hide your browser engine, version or OS, among other things - so your base is _**the crowd**_ (TB users, or Mullvad Browser users) and you go from there. It's not hard to extrapolate 1 in X users are in that group. These tests would work much better entropy wise if they were real world with much larger datasets

In reality, we start from a base of Mullvad Browser users (or TB users), and reduce entropy from there (taking into account equivalency). So for example, coveryourtracks says the entropy for timezone at UTC0 is 2.32 and 1 in 4.99 browsers use this - but the entropy is actually zero if you start from a smaller base. So we can ignore that metric - everyone is the same. Figures are not always what they appear

https://amiunique.org/stats - apparently Firefox is used by 38% of users. This is simply not even close - gecko based browsers are approx 3 to 4% of all worldwide users.  Linux is 23% of users, again, not even close. UTC0 is 30%, again, ludicrous

These sites are great for checking what metrics return, they are useless for entropy and you should always ignore any such figures. Unless you understand _how_ FPing and protection works, then don't try to second guess and make assumptions.

The only way to get an idea of entropy, is 1) math (e.g. UTC0 = all TB users, and TB users are 1 in 10000, so the result is 1 in 10000 - made up number) - and 2) by doing a survey with one result per profile in order to see the long thin tail of user buckets

Disclosure: I have been working with (not working for) FF and TB for years on fingerprinting

**Comment by Thorin-Oakenpants** [comment]
device ids - from memory, change per eTLD+1 + origin + scheme session as well, so you don't even need a new browser session. Fingerprints shouldn't be using device ids anyway - that's just asking for trouble and is baby 101 rookie numbers! ;)

**Comment by felschr** [comment]
In Tor Browser on NixOS I actually get "Not supported" for Media Devices on https://amiunique.org.
Is this normal or is this specific to the NixOS package?
Related: #62

**Comment by Thorin-Oakenpants** [comment]
> Is this normal

to save people hopping around issues - on TB, yes. The API is disabled

On MB it is enabled via webrtc so we expect results: 1 audio, 1 video (inputs)
