### ISSUE TITLE
same fingerprint across Linux distributions?

### ISSUE THREAD

**Issue by felschr** [mullvad/mullvad-browser#62]
I've been curious about the fingerprint of different Mullvad Browser (and Tor Browser) installations.
I know the fingerprint is different for Windows, Linux & macOS, but is there also a difference between Linux distributions & packages (official archive, Flatpak, Nixpkgs, AUR, ...)?

For example my fingerprints on https://abrahamjuliot.github.io/creepjs/ are the following on NixOS:

**Mullvad Browser 12.0.4:**
FP ID: 9c2e095780fbb23a9d5c917174a2549f53a03d16d2ed5d46959548a72ed5256e
Fuzzy: 76ec528b940a9bbe109938e94004645e1ffb083c0fcaa9f894b9000000000000
Diffs: 8c23528b940a9bbe109938e94004645e1f59f83c0faaa9f894b9000000000000

**Tor Browser 12.0.4:**
FP ID: 142dc25af0ff65814d938affdb3602a5d4a521403d369b890070bf85ecb853b9
Fuzzy: b25ff28b94039bbe1a99c8e940d46fff5f45283c0f3aa9f894b9000000000000
Diffs: e6dff28b94039bbe1a99c8e940d46fff5f97f83c0feaa9f894b9000000000000

I'd like to see others share their creepjs fingerprints in this issue (if it isn't unique!, be careful).
Please be sure to mention the browser version, OS, installation method & whether you made any configuration changes.

**Comment by felschr** [comment]
Might be of interest:
https://github.com/arkenfox/TZP
https://blog.torproject.org/browser-fingerprinting-introduction-and-challenges-ahead/

**Comment by Thorin-Oakenpants** [comment]
> Windows, Linux & macOS

There are also differences within those due to the platform version, e.g. fonts and font variants. There are differences that can detect 32bit vs 64bit. And there are over-arching issues that cause differences such measurements that show subpixels (dpi, devicePixelRatio, system scaling, etc)

this is the resist in resistFingerprinting - you go metric by metric, and protect the real value (allowing equivalency, e.g. per platform). As you cover more metrics, you make it harder and more costly for scripts to effectively track you vis FPing. Step two, build the crowd so all buckets of fingerprints get fatter and also make it harder

MB is already different to TB, and is not trying to be like TB. For starters it enabled media devices, webrtc ...

---

You said something about media devices on NixOS, but now I can't find it. You should have 1 audio + 1 video regardless of your hardware. Is this not the case?

**Comment by Thorin-Oakenpants** [comment]
> doesn't Mullvad Browser always use its own fonts

It uses the same as TB. RFP on FF is a completely different engineering.

So on Windows and Mac, a `whitelist` is used which includes some system fonts and a heap of bundled fonts. Those system fonts (and their variants such as bold, oblique, narrow) can vary. On Linux though, it sets a font config directory which is entirely the bundled fonts (and also uses a whitelist for ummm reasons)

https://github.com/arkenfox/TZP/blob/4c3947bddd1bac44c16bd31a7ea8e1d3a6d047b3/js/fonts.js#L27-L75

So Linux is very tight on font enumeration (detecting what fonts are available), Windows/Mac not so much. In an ideal world we would also bundle ALL fonts in windows + mac as well, but I believe the constraint right now is the sizes of CJK. It's only been six months since we overhauled this.

This is different to exploiting subpixels (measured sizes) which manifest everywhere (not just fonts), although fonts also have their own system/app aliasing rules etc

---

TB + media devices: correct, TB disabled it so you should get `none`, or a returned error or whatever the script decides

**Comment by Thorin-Oakenpants** [comment]
this is TZP 2.0 (not live), but you can use TZP 1.0 to check the results

![TZP2](https://user-images.githubusercontent.com/16656956/232135775-8b54fe07-3167-4199-b2b1-4f831dc7c116.png)

**Comment by Thorin-Oakenpants** [comment]
and for your amusement, since I can easily detect MB from TB via other means, here they are alerting you to issues should you change their settings

![TZP2](https://user-images.githubusercontent.com/16656956/232141666-0c3313ce-db2b-4a47-a708-a814123ed80a.png)

**Comment by Thorin-Oakenpants** [comment]
!remind me in a week @ruihildt

**Comment by Thorin-Oakenpants** [comment]
@ruihildt this is the same as my answers at #71

and some more info

in terms of defense it makes sense to leverage the platform and things you can't hide or lie about to be plausible or more compatible (e.g we change the `outputLatency` based on platform, fonts differ per platform for logistical reasons etc) 

but in terms of fingerprinting scripts it makes no sense at all (mostly). Scripts don't need to _tell_ you the os, or if you are in pb mode, etc - they just collect the data and the buckets will form naturally. And scripts can do what they want with a FP _after_ they have it, i.e determine what is noise or what degree of confidence to score a metric.

If you don't know what a test site is actually doing, don't guess. Just because a FP test site stays the same doesn't mean it's trackable, and just because it changes doesn't mean it isn't.

Also, no one knows. I mean we know some stuff just from math and how the protection is coded. But to get an idea of how many buckets something has, we really need to collect gecko FPs (in TB/MB/FF buckets) ... and you need real world studies, one FP per profile, to determine the entropy and actually _know_ if TB/MB's protections are working.
