### ISSUE TITLE
Support JPEG-XL image format

### ISSUE THREAD

**Issue by gianni-rosato** [mullvad/mullvad-browser#7]
Facebook, Adobe, Intel and the Video Electronics Standards Association, The Guardian, Flickr and SmugMug, Shopify, the Krita Foundation, and Serif Ltd have all voiced support for JPEG-XL as well as Google's research divison & Cloudinary. There are open source, permissively licensed patches available for Firefox-based & Chromium-based browsers currently that can be implemented with very little effort.

**Comment by throaway75245** [comment]
This is probably something that should be added in the upstream version of Firefox rather than independently here.  Adding it would put Mullvad on the hook for the security/privacy implications of the implementation which would be outside the scope of Mozilla's established security infrastructure and probably examined less in general to due the inherent low market share of a fork like this.

**Comment by gianni-rosato** [comment]
Mozilla is "neutral" on JPEG-XL & only includes support in Firefox Nightly behind a flag. It is unlikely at this point that JXL will be added upstream & Mozilla hasn't continued communicating with the public as to the specifics behind why. At this point, it is up to smaller forks to take on JXL support. See [Waterfox](https://github.com/WaterfoxCo/Waterfox/commit/90214aeca3ad9114293801205a86169419114656), [Pale Moon](https://www.palemoon.org/releasenotes.shtml), [Basilisk](https://www.basilisk-browser.org/releasenotes.shtml), [Mercury](https://github.com/Alex313031/Mercury/commit/c87b0271d587766a3780c2feb13673448ea5de75), & notably [LibreWolf](https://gitlab.com/librewolf-community/browser/source/-/commit/653df8e8fb74dd682422c0287f3156cb8ee79c87). Chromium-based [Thorium](https://github.com/Alex313031/Thorium/blob/main/infra/PATCHES.md) also features full support, & there are open issues & forum posts for other Chromium-based browsers such as [Brave](https://github.com/brave/brave-browser/issues/28411) and [Vivaldi](https://forum.vivaldi.net/topic/85153/adding-support-for-jpeg-xl-jxl-images/3). Chromium on OpenMandriva Linux ships patched to support JXL, & Bromite on Android also supports JXL behind a flag.

The community is passionately interested in JPEG-XL. I think a flag wouldn't hurt considering the amount of attention this image format has received compared to others like AVIF.

**Comment by Thorin-Oakenpants** [comment]
This was already rejected upstream at Tor Project - https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41664 - if Firefox adds it, great - if not then so be it. It's not worth the footgun and maintenance - let alone the fact that almost no site will use it because lack of support in major browsers

**Comment by gianni-rosato** [comment]
Shopify already has it deployed throughout every site that utilizes their services, if that makes a difference. Can you elaborate as to why it is not worth the "footgun" even just including it behind a flag like Librewolf does?

**Comment by Thorin-Oakenpants** [comment]
see the linked discussion at gitlab - it says it all. It needs investigation first (for privacy/fingerprint/security issues), then it needs to be maintained i.e keep an eye on it (which given mozilla's stance, things might get missed) = hence, footgun. Even things such as mozilla dropping it from something like RLBox (IDK if it uses RLBox, this is just an example) due to overhead or complexity or perf or something, and Tor Browser didn't know (not everyone can read 2000 closed bugzillas each month)

**Comment by gianni-rosato** [comment]
Thanks for your feedback, I'll relay what you've said to the JXL team. I appreciate your response. Hopefully sometime in the near future we can see Mullvad Browser support JPEG-XL

**Comment by ruihildt** [comment]
This will only be enabled if Tor Browser decide to ever enable it.
