### ISSUE TITLE
Add other search engines

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#70]
> Suggestion for future releases of Mullvad Browser to be bundled with other search engines (Brave Search, DuckDuckGo HTML, Startpage, Qwant, Searx, etc.) instead of Mullvad Leta, which is exclusive to Mullvad VPN users.

**Comment by kekkoudesu** [comment]
Mojeek is the one I use primarily.

I also use Kagi instead of Duckduckgo as a Bing/Google proxy. The only issue with Kagi is that it requires a login, and site data exceptions do not stick in permanent private browsing mode. I'd need to install the Kagi extension to persist across browser sessions.

**Comment by neglector** [comment]
That reminds me, is changing search engines (adding, removing, setting up default one) discouraged when it comes to fingerprinting? I would really like to switch to Brave if it doesn't go against browser's privacy design.

**Comment by ruihildt** [comment]
> That reminds me, is changing search engines (adding, removing, setting up default one) discouraged when it comes to fingerprinting? I would really like to switch to Brave if it doesn't go against browser's privacy design.

You are free to change the default search engine, it has no browser fingerprint implication.

If you use a trustworthy VPN and a browser effective against browser fingerprinting, it shouldn't matter what website you visit (and by extension, search engine). Of course if you login into a service, then you're back to have to trust them.

**Comment by kekkoudesu** [comment]
If it doesn't matter what search engine you use while not logged in with a VPN, why not use Bing (or Google, even)? These services are all fancy proxies for Bing in the end; Kagi is just the nicest one by virtue of combining several indexes together to get great results, not serving ads, having very clean SERPs, not requiring Javascript for any functions, allowing you to block certain sites or prioritize/deprioritize them in the rankings.

I did have a question about fingerprinting. I really don't like the omnibar, so I always add the separate dedicated searchbox and turn off `keyword.enabled` in `about:config`, so I have a dedicated URL bar + dedicated search bar. Would this impact the fingerprint?

**Comment by ruihildt** [comment]
> If it doesn't matter what search engine you use while not logged in with a VPN, why not use Bing (or Google, even)?

There are other considerations that can lead to use a service instead of another:
- Using a service that is focusing on privacy will always be better than using a service that's aggressively trying to collect as many data as possible (all things being equal). 
- Which business model you want to support?
- "defense in depth": if one layer of protection fails, you'll still be protected by the next layer, etc.

**Comment by ruihildt** [comment]
> I did have a question about fingerprinting. I really don't like the omnibar, so I always add the separate dedicated searchbox and turn off `keyword.enabled` in `about:config`, so I have a dedicated URL bar + dedicated search bar. Would this impact the fingerprint?

I would say this has no impact on the browser fingerprint, but I will check and come back with a more definitive answer.

**Comment by kekkoudesu** [comment]
> There are other considerations that can lead to use a service instead of another:
> 
>     * Using a service that is focusing on privacy will always be better than using a service that's aggressively trying to collect as many data as possible (all things being equal).
> 
>     * "defense in depth": if one layer of protection fails, you'll still be protected by the next layer, etc.

This is all well and good, and I can agree with these arguments.

>     * Which business model you want to support?

An interesting and complicated question. All Bing proxies are required to use Microsoft Advertising if they choose to display advertising alongside their results (and that is the way most proxies choose to monetize their service). So, when you are using Duckduckgo, Ecosia, Swisscows, Yahoo, or almost any other Bing proxy, you are supporting Microsoft's ad-based business model. 

When you purchase a Kagi subscription, you are still supporting Microsoft because they patronize the Bing API ([which recently surged at least 5 times in price](https://www.microsoft.com/en-us/bing/apis/pricing-update) quickly following the unveiling of the new Bing AI feature, so if you are seeing more ads on Duckduckgo and other proxies, this is why), but you don't see ads, and I think it's generally the best search experience. While I don't like the idea of paying Microsoft money, I think it is a far better business model where the searcher's and the business's interests are aligned. With most search engines, you aren't the customer; advertising agencies are.

But I don't think Kagi is sustainable while relying on Bing and Google's results. Even if Kagi is interested in taking that business model to the market, Bing doesn't seem to be. That recent price bump has definitely hurt them, and I can't imagine that will be the end of it. Independent indexes are the future, I believe.

When you use Mojeek, for example, you aren't supporting Microsoft, Google, or any companies which monetize their users' data. Mojeek still has ads. Brave Search, likewise, monetizes their search service with their own ads service and through premium subscriptions.

Personally, I can only see Microsoft tightening the noose on Bing proxies over time. They were useful to compete with Google, but they now have a much more promising method of competing with Google.

And speaking of which, what is "Mullvad Leta"? This search engine is bundled with the browser, but I can't find any information on it, and not being a Mullvad subscriber, it is not accessible to me. The idea of bundling a search engine with a VPN service is an interesting one. It provides some insulation from price rises like the March one, without compromising incentives.

All this to say, some users are quite passionate about their choice of search engine :)

> I would say this has no impact on the browser fingerprint, but I will check and come back with a more definitive answer.

Thank you.

**Comment by yanagibashi-mt** [comment]
@kekkoudesu This page should be accessible whether you are a customer of Mullvad or not: https://leta.mullvad.net/faq It is a "fancy Google proxy", while not being quite as fancy as Kagi.

>The idea of bundling a search engine with a VPN service is an interesting one. It provides some insulation from price rises like the March one, without compromising incentives.

Agreed. It's an interesting aspect. Makes me want to try their VPN service just for the search, as it might be an alternative to Kagi for me which I have been using so far.

**Comment by ruihildt** [comment]
> And speaking of which, what is "Mullvad Leta"? This search engine is bundled with the browser, but I can't find any information on it, and not being a Mullvad subscriber, it is not accessible to me. The idea of bundling a search engine with a VPN service is an interesting one. It provides some insulation from price rises like the March one, without compromising incentives.

Mullvad Leta has an FAQ answering some of those questions (viewable only when logged in)

> **Did you make your own search engine from scratch?**
> [#](https://leta.mullvad.net/faq#made-from-scratch)
> 
> We did not, we made a front end to the Google Search API.
> 
> Our search engine performs the searches on behalf of our users. This means that rather than using Google Search directly, our Leta server makes the requests.
> 
> Searching by proxy in other words.

I'm not able to comment more on Mullvad Leta as it has not been officially announced. Stay tuned.

**Comment by ruihildt** [comment]
> An interesting and complicated question.

Agreed, I am personally not 100% happy with any of the current solutions on the market. ;)

**Comment by Thorin-Oakenpants** [comment]
> I would say this [search bar] has no impact on the browser fingerprint, but I will check and come back with a more definitive answer.

web content can't directly access chrome properties and the search bar doesn't alter any external factors that could be problematic **_in some circumstances_** (such as changing densities, padding on the fly), in which case we are still protected by letterboxing

**Comment by kekkoudesu** [comment]
> web content can't directly access chrome properties and the search bar doesn't alter any external factors that could be problematic **_in some circumstances_** (such as changing densities, padding on the fly), in which case we are still protected by letterboxing

Good to know. So, if I used a completely custom userChrome with Mullvad Browser (say, [Firefox Gnome Theme](https://github.com/rafaelmardojai/firefox-gnome-theme)), my understanding is that because sites cannot access chrome properties, they wouldn't know I'm using a custom userChrome.

**Comment by kekkoudesu** [comment]
For Kagi users:

Go here and copy the session link: https://kagi.com/settings?p=user_details

Go to that URL in Mullvad Browser. Click the omnibar, and start typing to bring up the dropdown menu. Click the favicon for Kagi Search with the `+` badge on top of it, and you've added the Kagi search engine with that session token. It will persist even when you restart Mullvad Browser. This works because the OpenSearch document linked by Kagi changes when accessed with the session token as a query parameter.

If you need to revoke this session token, as Kagi says:

> To invalidate this token, simply log out.

Then delete the search engine and add it again using these steps. No cookie persistence required!

**Comment by BML7** [comment]
I was wondering if you could please add Metager by default for future updates. It would be great to click on the label and have Mullvad Leta,DDG,Metager, Brave...

Metager does not track you and you can also use their anonymous proxy to open most pages. On top of that it is outide the USA legislation, not like DDG or Brave.

**Comment by ruihildt** [comment]
We'll be adding the following search engines to the default list to start with:

- Startpage https://www.startpage.com/
- Mojeek https://www.mojeek.com/
- Brave Search https://search.brave.com/
- Metager https://metager.org/
- DuckDuckGo (HTML): https://html.duckduckgo.com/html/

**Comment by ruihildt** [comment]
@AutonomousCat This will be part of 13.0 planned for the end of September.

**Comment by Thorin-Oakenpants** [comment]
https://whattrainisitnow.com/calendar/ - you may need to toggle "past releases" since it's a living document, to get a full picture

TB/MB use ESR, so that gives 3 or 4 (depending on how you look at it) releases until the end-of-life (EOL) of the previous ESR lifecycle to get it ready. So, in this cycle, as soon as 115 was out, we started rebasing, auditing etc.

26th Sept was our target date, This is where the old ESR102 was no longer supported upstream. But we can't ship TB/MB13 due to some delays/"blockers" - trust me, they're all working on it. Meanwhile, if they have to, 12.0 can continue with backported security patches if necessary

I _think_ it's about a week or two away at most, but don't quote me

**Comment by ruihildt** [comment]
> it's about a week or two away at most

Correct. :)

**Comment by BML7** [comment]
Thank you so much!! to those who developed the new Mullvad Browser 13.0. Your hard work is much appreciated. I am very happy with it and Metager as an option by default. Amazing!

**Comment by ruihildt** [comment]
@BML7 Happy to hear! :)

Fixed in Mullvad Browser 13.0.

See: https://github.com/mullvad/mullvad-browser/releases/tag/13.0

**Comment by BML7** [comment]
Hi Ruihildt, I was having a look at Swisscows. I think it would be a great option for search engines as it is not located in USA or Europe. Their jurisdiction is Switzerland https://swisscows.com/en I checked with ublock origin and no tracks were found. All the best!
