### ISSUE TITLE
How many buckets of users from Operating Systems?

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#71]
> It is mentioned that "Mullvad Browser is specifically engineered to have a nearly identical (we're not perfect!) fingerprint across its users per operating system." Does this mean that Mullvad Browser users are placed into 3 possible OS fingerprinting buckets (Windows, macOS, Linux) depending on the OS ("per operating system")?

**Comment by Thorin-Oakenpants** [comment]
This is something that should also be part of TB's `a new/updated design document (dreaming big again)`

**Comment by Thorin-Oakenpants** [comment]
Do you want me to answer this with some back of the napkin maths?

**Comment by ruihildt** [comment]
> This is something that should also be part of TB's `a new/updated design document (dreaming big again)`

Link to the issue: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41808

**Comment by ruihildt** [comment]
> Do you want me to answer this with some back of the napkin maths?

Yes please. :)

**Comment by Thorin-Oakenpants** [comment]
copy pasted (and edited)

```
<thorin> things you cannot hide - 3 x OS (we will ignore android) .. but each OS is slightly different
<thorin> so windows + linux we can tell browser bitness (32 vs 64) and mac's are basically always 64 bit anyway
<thorin> so .. 2 + 2 + 2 .. capisce
<thorin> type
<thorin> I meant 2 + 2 + 1
<thorin> lets continue
<thorin> on windows we can get at least 2 fonts-buckets (due to font diffs in 7/8/10) .. but mac is solid and linux is all bundled
<thorin> so it's now 4 windows + 2 linux + 1 mac
<thorin> there's more that is OS specific .. but lets call it quits and say 7 basic OS buckets
<ruihildt[m]> You're welcome to add this to the ticket, so I can close it.
<thorin> now metrics that affect all OSes .. we have say 8 really common window sizes, we have 42 languages ....
<thorin> can you see where I'm going?
<thorin> 7 x 8 x 38 (well, 22 in MB)
<thorin> so that's 2,128 possible FPs so far (1,232 in MB)
<thorin> and I'm barely scratching the surface
<thorin> which is nowhere near 3
```

lemme make that bigger for you to all see

##  so that's 2,128 possible FPs so far (1,232 in MB), and I'm barely scratching the surface, which is nowhere near 3

so that's _possible_ FPs and this does not mean _**entropy**_ - entropy is the real world spread of users in each bucket - some will be empty, some will be overloaded

## TB/MB users have a common FP is a myth and you all need to stop spreading it

@ruihildt feel free to close this now :)

**Comment by Thorin-Oakenpants** [comment]
> <thorin> there's more that is OS specific .. but lets call it quits and say 7 basic OS buckets

so OP asked about OS stuff, not overall fingerprints, and I can tell you that we can
- 10 x it at least (because of something)
- double it (because of something else)
- double it again
- double it again
- and i'm not even thinking too hard - maybe double it a couple more times

but these aren't necessarily limited to specific OSes but are likely closely aligned

**Comment by Thorin-Oakenpants** [comment]
don't ask me to explain any more, please :)
