### ISSUE TITLE
Security level page and popup "Learn more" broken

### ISSUE THREAD

**Issue by throaway75245** [mullvad/mullvad-browser#9]
The "Learn more" link in the security level settings page and popup goes to about:manual#security-settings which is broken. The page should either be restored with proper verbiage, the link changed to something else, e.g. FAQ on mullvad's website, or removed.

**Comment by ruihildt** [comment]
Thanks, we have noticed this too late! It will be fixed in the next version.

**Comment by coffeemesh** [comment]
@throaway75245 you can find some details [here ](https://github.com/mullvad/mullvad-browser/commit/4dbcc25314bf28a764bf4707d67fc1998d35d063) . 
I was curious how and where one would make such a change so I found it, at least I think so. 
@ruihildt would these be the two required changes which fixes this issue or are there more steps to it, that I am missing? (Just trying to understand how such complex software get updated.)

**Comment by ruihildt** [comment]
@coffeemesh This is going to be fixed by the Mullvad Browser developers in the next version.
As soon as the update will be made available, the browser will auto-update.

**Comment by coffeemesh** [comment]
Thank you @ruihildt for taking the time to respond, very kind of you. I actually didn't mean to indirectly ask if and when the fix was going to happen but was actually rather trying to understand the fix more from a techincal standpoint to educate myself a bit. I checked some more commits out and they were quite insightful! Very cool stuff you guys are doing!

**Comment by ruihildt** [comment]
Fixed in [Mullvad 12.0.5](https://github.com/mullvad/mullvad-browser/releases/tag/mullvad-browser-102.10.0esr-12.0-2-build2)
