### ISSUE TITLE
Is it possible to make the following changes, corrections and implementations suggested below?

### ISSUE THREAD

**Issue by serial02** [mullvad/mullvad-browser#92]
Hello Mullvad Team

 You can make the following updates, fixes and implementations below:

1º It is possible to make other languages ​​available for the next version of Mullvad Browser, since there is a database of languages ​​in the Firefox base.

2º Is it possible to implement the option to open in predefined Facebook container tabs, since the official extension can be installed, but the option to open in container tabs does not exist in the Mullvad Browser Menu?

![Capturar_select-area_20230522140444](https://github.com/mullvad/mullvad-browser/assets/32621790/a18495ab-b544-4869-a162-4905c3d114db)

3º NoScript does not keep the permissions or refusals made during website navigation.  Restarting the browser, all settings already made return to the application's default.

**Comment by Thorin-Oakenpants** [comment]
> 3º NoScript does not keep

see https://github.com/mullvad/mullvad-browser/issues/41#issuecomment-1499533932

**Comment by Thorin-Oakenpants** [comment]
> 2º containers

containers are incompatible with private browsing windows, and MB starts in PB mode

**Comment by Thorin-Oakenpants** [comment]
^ also, I should point out that MB already has FPI (First Party Isolation), so containers don't offer any additional **protection**

**Comment by serial02** [comment]
> containers are incompatible with private browsing windows, and MB starts in PB mode

Hello @Thorin-Oakenpants 

 Can you tell me why the container options exist on the platform?

![Captura de tela de 2023-05-26 14-17-33](https://github.com/mullvad/mullvad-browser/assets/32621790/3cad537e-d603-494d-8b30-808b1c2fe3af)

What about language options?  Will it be added?

**Comment by Thorin-Oakenpants** [comment]
You will have to ask Mullvad about languages

---

As for containers, they are not available in Private Mode windows - long-click or right-click the `+` icon on the tabstrip

Here is Firefox, normal window on the left, private mode window on the right
![containers](https://github.com/mullvad/mullvad-browser/assets/16656956/0db4231f-907a-47f1-b9a6-23d4c181a71a)

`about:preferences#containers` being availble via the urlbar is a Firefox UX bug. It's not directly available in settings, you have to actually use that anchor

In order to get containers to actually work, **_and don;t dfo this_** you have to
 - change Mullvad's settings to not start in PB mode?
   - Settings > Privacy & Security > History > Always use private browsing mode (unchecked)
- change two prefs: `privacy.userContext.ui.enabled` and `privacy.userContext.enabled`

**Comment by ruihildt** [comment]
1 -  see #93 
2 - answered
3 - answered
